% ---- CARGAR ARCHIVO ----

data = load('C:\Users\marti\Desktop\Trabajo Final\Parte 3\Sim i9\Simulacion_20260601_120100\Data_D2p500e-9_T22000ms.mat');

%======================================================
% MAPA D-T2 + PROYECCION T2
%======================================================

figure(100)
clf
set(gcf,...
'Units','pixels',...
'Position',[100 100 700 700])
movegui(gcf,'center') % centra la ventana en la pantalla, evita que se corte arriba

%------------------------------------------------------
% Layout
%------------------------------------------------------

leftMargin = 0.15;
bottom     = 0.12;
mapW = 0.65;
mapH = 0.60;
projH = 0.12;
gapMapProj = 0.01;

%======================================================
% PROYECCION T2
%======================================================

axProj = axes('Position',...
    [leftMargin,...
     bottom+mapH+gapMapProj,...
     mapW,...
     projH]);
semilogx(data.T2_axis,...
         data.proj_T2,...
'b',...
'LineWidth',2)
hold on
y_left = interp1(data.T2_axis,...
                 data.proj_T2,...
                 data.T2_left);
y_right = interp1(data.T2_axis,...
                  data.proj_T2,...
                  data.T2_right);
plot(data.T2_left,...
     y_left,...
'ro',...
'MarkerSize',9,...
'LineWidth',2)
plot(data.T2_right,...
     y_right,...
'ro',...
'MarkerSize',9,...
'LineWidth',2)
plot([data.T2_left data.T2_right],...
     [0.5 0.5],...
'r',...
'LineWidth',2)
yline(0.5,...
'--k',...
'LineWidth',1.2)
hold off
set(gca,...
'XScale','log',...
'XTickLabel',[],...
'FontSize',12,...
'Box','on')
xlim([min(data.T2_axis) max(data.T2_axis)])
ylabel('')

%======================================================
% MAPA D-T2
%======================================================

axMap = axes('Position',...
    [leftMargin,...
     bottom,...
     mapW,...
     mapH]);
contourf(data.T2_axis,...
         data.D_axis,...
         data.S,...
         90,...
'LineStyle','none')
set(gca,...
'XScale','log',...
'YScale','log',...
'FontSize',14,...
'Box','on')
xlabel('T_2(s)','FontSize',18)
ylabel('D(m^2/s)','FontSize',18)
xlim([min(data.T2_axis) max(data.T2_axis)])
ylim([min(data.D_axis) max(data.D_axis)])

% ---- COLORMAP QUE ARRANCA EN BLANCO ----
% Se toma 'parula' como base y se antepone una rampa de blanco -> primer
% color de parula, para que el amplitud=0 se vea blanco en vez de azul oscuro.

nBase = 256;
base = parula(nBase);
nRamp = 32; % cantidad de pasos para pasar de blanco a azul oscuro
ramp = [linspace(1,base(1,1),nRamp)', ...
        linspace(1,base(1,2),nRamp)', ...
        linspace(1,base(1,3),nRamp)'];
cmapBlanco = [ramp; base];
colormap(axMap, cmapBlanco)

cb = colorbar;
cb.Label.String = 'Amplitud';
cb.FontSize = 12;

%======================================================
% ALINEAR EJES (despues del colorbar, que angosta axMap)
%======================================================
% El colorbar redimensiona axMap; hay que leer su posicion real
% y aplicarsela a axProj para que ambos paneles queden alineados.

posMap = get(axMap, 'Position');
posProj = get(axProj, 'Position');
set(axProj, 'Position', [posMap(1), posProj(2), posMap(3), posProj(4)]);

linkaxes([axProj axMap],'x')